export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  BAD_REQUEST = 'BAD_REQUEST',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // Savings
  SAVINGS_PRODUCT_NOT_FOUND = 'SAVINGS_PRODUCT_NOT_FOUND',
  SAVINGS_GOAL_NOT_FOUND = 'SAVINGS_GOAL_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  WITHDRAWAL_NOT_FOUND = 'WITHDRAWAL_NOT_FOUND',
  DEPOSIT_FAILED = 'DEPOSIT_FAILED',
  WITHDRAWAL_FAILED = 'WITHDRAWAL_FAILED',
  MINIMUM_AMOUNT_NOT_MET = 'MINIMUM_AMOUNT_NOT_MET',

  // Governance
  PROPOSAL_NOT_FOUND = 'PROPOSAL_NOT_FOUND',
  INVALID_GOVERNANCE_STATE = 'INVALID_GOVERNANCE_STATE',
  ALREADY_VOTED = 'ALREADY_VOTED',
  NO_VOTING_POWER = 'NO_VOTING_POWER',
  PROPOSAL_NOT_ACTIVE = 'PROPOSAL_NOT_ACTIVE',

  // Transactions
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  INVALID_TRANSACTION_STATE = 'INVALID_TRANSACTION_STATE',

  // Disputes
  DISPUTE_NOT_FOUND = 'DISPUTE_NOT_FOUND',
  INVALID_DISPUTE_STATE = 'INVALID_DISPUTE_STATE',

  // Claims
  CLAIM_NOT_FOUND = 'CLAIM_NOT_FOUND',
  INVALID_CLAIM_STATE = 'INVALID_CLAIM_STATE',

  // Referrals
  REFERRAL_NOT_FOUND = 'REFERRAL_NOT_FOUND',
  SELF_REFERRAL = 'SELF_REFERRAL',
  REFERRAL_ALREADY_USED = 'REFERRAL_ALREADY_USED',

  // Blockchain / RPC
  SOROBAN_RPC_TIMEOUT = 'SOROBAN_RPC_TIMEOUT',
  SOROBAN_RPC_EXHAUSTED = 'SOROBAN_RPC_EXHAUSTED',
  BLOCKCHAIN_ERROR = 'BLOCKCHAIN_ERROR',

  // Database
  DB_CONNECTION_ERROR = 'DB_CONNECTION_ERROR',

  // Idempotency
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
}
