export enum WebhookVerificationErrorCode {
  MISSING_SIGNATURE = 'WEBHOOK_VERIFICATION_MISSING_SIGNATURE',
  INVALID_SIGNATURE = 'WEBHOOK_VERIFICATION_INVALID_SIGNATURE',
  MISSING_TIMESTAMP = 'WEBHOOK_VERIFICATION_MISSING_TIMESTAMP',
  INVALID_TIMESTAMP = 'WEBHOOK_VERIFICATION_INVALID_TIMESTAMP',
  REPLAYED_NONCE = 'WEBHOOK_VERIFICATION_REPLAYED_NONCE',
  MISSING_NONCE = 'WEBHOOK_VERIFICATION_MISSING_NONCE',
  INVALID_BODY = 'WEBHOOK_VERIFICATION_INVALID_BODY',
}

export type WebhookVerificationErrorPayload = {
  code: WebhookVerificationErrorCode;
  message: string;
  details?: Record<string, unknown>;
};

